# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
#test
name: .NET

on:
  push:
    branches: ["main","release/QA","release/Production"]
     
  pull_request:
    branches: ["main","release/QA","release/Production"]
     

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore D:\a\dotnet-minimal-web-api-example\dotnet-minimal-web-api-example\DotNetMinimalAPIDemo
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRETKEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: dotnet-minimal-web-api-example
        IMAGE_TAG: dotnet-minimal-web-api-example
      run: |
        docker build -t dotnet-minimal-web-api-example .
        docker tag dotnet-minimal-web-api-example:latest 020494211308.dkr.ecr.us-east-1.amazonaws.com/dotnet-minimal-web-api-example:latest
        #docker login -u "jaswant1306@gmail.com" -p "dckr_pat_6knTuyeU0O1NbDjDOyDkr7m77EM" docker.io
        docker push 020494211308.dkr.ecr.us-east-1.amazonaws.com/dotnet-minimal-web-api-example:latest   
    - name: Docker Build
      run: docker build .
    - name: Build
      run: dotnet build --no-restore D:\a\dotnet-minimal-web-api-example\dotnet-minimal-web-api-example\DotNetMinimalAPIDemo
    #- name: Test
      #run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish D:\a\dotnet-minimal-web-api-example\dotnet-minimal-web-api-example\DotNetMinimalAPIDemo\DotNetMinimalAPIDemo.csproj -c Release -o PublishedArtifacts  
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PublishedArtifacts
        path: D:\a\dotnet-minimal-web-api-example\dotnet-minimal-web-api-example\PublishedArtifacts\**
        if-no-files-found: error
    
